/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LessonRouteRouteImport } from './routes/lesson/route'
import { Route as siteRouteRouteImport } from './routes/(site)/route'
import { Route as marketingRouteRouteImport } from './routes/(marketing)/route'
import { Route as LessonIndexRouteImport } from './routes/lesson/index'
import { Route as marketingIndexRouteImport } from './routes/(marketing)/index'
import { Route as siteShopIndexRouteImport } from './routes/(site)/shop/index'
import { Route as siteQuestsIndexRouteImport } from './routes/(site)/quests/index'
import { Route as siteLearnIndexRouteImport } from './routes/(site)/learn/index'
import { Route as siteLeaderboardIndexRouteImport } from './routes/(site)/leaderboard/index'
import { Route as siteCoursesIndexRouteImport } from './routes/(site)/courses/index'
import { Route as marketingTermsIndexRouteImport } from './routes/(marketing)/terms/index'
import { Route as marketingPrivacyIndexRouteImport } from './routes/(marketing)/privacy/index'

const LessonRouteRoute = LessonRouteRouteImport.update({
  id: '/lesson',
  path: '/lesson',
  getParentRoute: () => rootRouteImport,
} as any)
const siteRouteRoute = siteRouteRouteImport.update({
  id: '/(site)',
  getParentRoute: () => rootRouteImport,
} as any)
const marketingRouteRoute = marketingRouteRouteImport.update({
  id: '/(marketing)',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonIndexRoute = LessonIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LessonRouteRoute,
} as any)
const marketingIndexRoute = marketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => marketingRouteRoute,
} as any)
const siteShopIndexRoute = siteShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => siteRouteRoute,
} as any)
const siteQuestsIndexRoute = siteQuestsIndexRouteImport.update({
  id: '/quests/',
  path: '/quests/',
  getParentRoute: () => siteRouteRoute,
} as any)
const siteLearnIndexRoute = siteLearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => siteRouteRoute,
} as any)
const siteLeaderboardIndexRoute = siteLeaderboardIndexRouteImport.update({
  id: '/leaderboard/',
  path: '/leaderboard/',
  getParentRoute: () => siteRouteRoute,
} as any)
const siteCoursesIndexRoute = siteCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => siteRouteRoute,
} as any)
const marketingTermsIndexRoute = marketingTermsIndexRouteImport.update({
  id: '/terms/',
  path: '/terms/',
  getParentRoute: () => marketingRouteRoute,
} as any)
const marketingPrivacyIndexRoute = marketingPrivacyIndexRouteImport.update({
  id: '/privacy/',
  path: '/privacy/',
  getParentRoute: () => marketingRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/lesson': typeof LessonRouteRouteWithChildren
  '/': typeof marketingIndexRoute
  '/lesson/': typeof LessonIndexRoute
  '/privacy': typeof marketingPrivacyIndexRoute
  '/terms': typeof marketingTermsIndexRoute
  '/courses': typeof siteCoursesIndexRoute
  '/leaderboard': typeof siteLeaderboardIndexRoute
  '/learn': typeof siteLearnIndexRoute
  '/quests': typeof siteQuestsIndexRoute
  '/shop': typeof siteShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof marketingIndexRoute
  '/lesson': typeof LessonIndexRoute
  '/privacy': typeof marketingPrivacyIndexRoute
  '/terms': typeof marketingTermsIndexRoute
  '/courses': typeof siteCoursesIndexRoute
  '/leaderboard': typeof siteLeaderboardIndexRoute
  '/learn': typeof siteLearnIndexRoute
  '/quests': typeof siteQuestsIndexRoute
  '/shop': typeof siteShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(marketing)': typeof marketingRouteRouteWithChildren
  '/(site)': typeof siteRouteRouteWithChildren
  '/lesson': typeof LessonRouteRouteWithChildren
  '/(marketing)/': typeof marketingIndexRoute
  '/lesson/': typeof LessonIndexRoute
  '/(marketing)/privacy/': typeof marketingPrivacyIndexRoute
  '/(marketing)/terms/': typeof marketingTermsIndexRoute
  '/(site)/courses/': typeof siteCoursesIndexRoute
  '/(site)/leaderboard/': typeof siteLeaderboardIndexRoute
  '/(site)/learn/': typeof siteLearnIndexRoute
  '/(site)/quests/': typeof siteQuestsIndexRoute
  '/(site)/shop/': typeof siteShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/lesson'
    | '/'
    | '/lesson/'
    | '/privacy'
    | '/terms'
    | '/courses'
    | '/leaderboard'
    | '/learn'
    | '/quests'
    | '/shop'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/lesson'
    | '/privacy'
    | '/terms'
    | '/courses'
    | '/leaderboard'
    | '/learn'
    | '/quests'
    | '/shop'
  id:
    | '__root__'
    | '/(marketing)'
    | '/(site)'
    | '/lesson'
    | '/(marketing)/'
    | '/lesson/'
    | '/(marketing)/privacy/'
    | '/(marketing)/terms/'
    | '/(site)/courses/'
    | '/(site)/leaderboard/'
    | '/(site)/learn/'
    | '/(site)/quests/'
    | '/(site)/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  marketingRouteRoute: typeof marketingRouteRouteWithChildren
  siteRouteRoute: typeof siteRouteRouteWithChildren
  LessonRouteRoute: typeof LessonRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lesson': {
      id: '/lesson'
      path: '/lesson'
      fullPath: '/lesson'
      preLoaderRoute: typeof LessonRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(site)': {
      id: '/(site)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof siteRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(marketing)': {
      id: '/(marketing)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof marketingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/': {
      id: '/lesson/'
      path: '/'
      fullPath: '/lesson/'
      preLoaderRoute: typeof LessonIndexRouteImport
      parentRoute: typeof LessonRouteRoute
    }
    '/(marketing)/': {
      id: '/(marketing)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof marketingIndexRouteImport
      parentRoute: typeof marketingRouteRoute
    }
    '/(site)/shop/': {
      id: '/(site)/shop/'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof siteShopIndexRouteImport
      parentRoute: typeof siteRouteRoute
    }
    '/(site)/quests/': {
      id: '/(site)/quests/'
      path: '/quests'
      fullPath: '/quests'
      preLoaderRoute: typeof siteQuestsIndexRouteImport
      parentRoute: typeof siteRouteRoute
    }
    '/(site)/learn/': {
      id: '/(site)/learn/'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof siteLearnIndexRouteImport
      parentRoute: typeof siteRouteRoute
    }
    '/(site)/leaderboard/': {
      id: '/(site)/leaderboard/'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof siteLeaderboardIndexRouteImport
      parentRoute: typeof siteRouteRoute
    }
    '/(site)/courses/': {
      id: '/(site)/courses/'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof siteCoursesIndexRouteImport
      parentRoute: typeof siteRouteRoute
    }
    '/(marketing)/terms/': {
      id: '/(marketing)/terms/'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof marketingTermsIndexRouteImport
      parentRoute: typeof marketingRouteRoute
    }
    '/(marketing)/privacy/': {
      id: '/(marketing)/privacy/'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof marketingPrivacyIndexRouteImport
      parentRoute: typeof marketingRouteRoute
    }
  }
}

interface marketingRouteRouteChildren {
  marketingIndexRoute: typeof marketingIndexRoute
  marketingPrivacyIndexRoute: typeof marketingPrivacyIndexRoute
  marketingTermsIndexRoute: typeof marketingTermsIndexRoute
}

const marketingRouteRouteChildren: marketingRouteRouteChildren = {
  marketingIndexRoute: marketingIndexRoute,
  marketingPrivacyIndexRoute: marketingPrivacyIndexRoute,
  marketingTermsIndexRoute: marketingTermsIndexRoute,
}

const marketingRouteRouteWithChildren = marketingRouteRoute._addFileChildren(
  marketingRouteRouteChildren,
)

interface siteRouteRouteChildren {
  siteCoursesIndexRoute: typeof siteCoursesIndexRoute
  siteLeaderboardIndexRoute: typeof siteLeaderboardIndexRoute
  siteLearnIndexRoute: typeof siteLearnIndexRoute
  siteQuestsIndexRoute: typeof siteQuestsIndexRoute
  siteShopIndexRoute: typeof siteShopIndexRoute
}

const siteRouteRouteChildren: siteRouteRouteChildren = {
  siteCoursesIndexRoute: siteCoursesIndexRoute,
  siteLeaderboardIndexRoute: siteLeaderboardIndexRoute,
  siteLearnIndexRoute: siteLearnIndexRoute,
  siteQuestsIndexRoute: siteQuestsIndexRoute,
  siteShopIndexRoute: siteShopIndexRoute,
}

const siteRouteRouteWithChildren = siteRouteRoute._addFileChildren(
  siteRouteRouteChildren,
)

interface LessonRouteRouteChildren {
  LessonIndexRoute: typeof LessonIndexRoute
}

const LessonRouteRouteChildren: LessonRouteRouteChildren = {
  LessonIndexRoute: LessonIndexRoute,
}

const LessonRouteRouteWithChildren = LessonRouteRoute._addFileChildren(
  LessonRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  marketingRouteRoute: marketingRouteRouteWithChildren,
  siteRouteRoute: siteRouteRouteWithChildren,
  LessonRouteRoute: LessonRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
