/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as siteRouteRouteImport } from './routes/(site)/route'
import { Route as marketingRouteRouteImport } from './routes/(marketing)/route'
import { Route as marketingIndexRouteImport } from './routes/(marketing)/index'
import { Route as siteShopIndexRouteImport } from './routes/(site)/shop/index'
import { Route as siteQuestsIndexRouteImport } from './routes/(site)/quests/index'
import { Route as siteLearnIndexRouteImport } from './routes/(site)/learn/index'
import { Route as siteLeaderboardIndexRouteImport } from './routes/(site)/leaderboard/index'
import { Route as siteCoursesIndexRouteImport } from './routes/(site)/courses/index'

const siteRouteRoute = siteRouteRouteImport.update({
  id: '/(site)',
  getParentRoute: () => rootRouteImport,
} as any)
const marketingRouteRoute = marketingRouteRouteImport.update({
  id: '/(marketing)',
  getParentRoute: () => rootRouteImport,
} as any)
const marketingIndexRoute = marketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => marketingRouteRoute,
} as any)
const siteShopIndexRoute = siteShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => siteRouteRoute,
} as any)
const siteQuestsIndexRoute = siteQuestsIndexRouteImport.update({
  id: '/quests/',
  path: '/quests/',
  getParentRoute: () => siteRouteRoute,
} as any)
const siteLearnIndexRoute = siteLearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => siteRouteRoute,
} as any)
const siteLeaderboardIndexRoute = siteLeaderboardIndexRouteImport.update({
  id: '/leaderboard/',
  path: '/leaderboard/',
  getParentRoute: () => siteRouteRoute,
} as any)
const siteCoursesIndexRoute = siteCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => siteRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof marketingIndexRoute
  '/courses': typeof siteCoursesIndexRoute
  '/leaderboard': typeof siteLeaderboardIndexRoute
  '/learn': typeof siteLearnIndexRoute
  '/quests': typeof siteQuestsIndexRoute
  '/shop': typeof siteShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof marketingIndexRoute
  '/courses': typeof siteCoursesIndexRoute
  '/leaderboard': typeof siteLeaderboardIndexRoute
  '/learn': typeof siteLearnIndexRoute
  '/quests': typeof siteQuestsIndexRoute
  '/shop': typeof siteShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(marketing)': typeof marketingRouteRouteWithChildren
  '/(site)': typeof siteRouteRouteWithChildren
  '/(marketing)/': typeof marketingIndexRoute
  '/(site)/courses/': typeof siteCoursesIndexRoute
  '/(site)/leaderboard/': typeof siteLeaderboardIndexRoute
  '/(site)/learn/': typeof siteLearnIndexRoute
  '/(site)/quests/': typeof siteQuestsIndexRoute
  '/(site)/shop/': typeof siteShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/courses' | '/leaderboard' | '/learn' | '/quests' | '/shop'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/courses' | '/leaderboard' | '/learn' | '/quests' | '/shop'
  id:
    | '__root__'
    | '/(marketing)'
    | '/(site)'
    | '/(marketing)/'
    | '/(site)/courses/'
    | '/(site)/leaderboard/'
    | '/(site)/learn/'
    | '/(site)/quests/'
    | '/(site)/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  marketingRouteRoute: typeof marketingRouteRouteWithChildren
  siteRouteRoute: typeof siteRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(site)': {
      id: '/(site)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof siteRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(marketing)': {
      id: '/(marketing)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof marketingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(marketing)/': {
      id: '/(marketing)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof marketingIndexRouteImport
      parentRoute: typeof marketingRouteRoute
    }
    '/(site)/shop/': {
      id: '/(site)/shop/'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof siteShopIndexRouteImport
      parentRoute: typeof siteRouteRoute
    }
    '/(site)/quests/': {
      id: '/(site)/quests/'
      path: '/quests'
      fullPath: '/quests'
      preLoaderRoute: typeof siteQuestsIndexRouteImport
      parentRoute: typeof siteRouteRoute
    }
    '/(site)/learn/': {
      id: '/(site)/learn/'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof siteLearnIndexRouteImport
      parentRoute: typeof siteRouteRoute
    }
    '/(site)/leaderboard/': {
      id: '/(site)/leaderboard/'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof siteLeaderboardIndexRouteImport
      parentRoute: typeof siteRouteRoute
    }
    '/(site)/courses/': {
      id: '/(site)/courses/'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof siteCoursesIndexRouteImport
      parentRoute: typeof siteRouteRoute
    }
  }
}

interface marketingRouteRouteChildren {
  marketingIndexRoute: typeof marketingIndexRoute
}

const marketingRouteRouteChildren: marketingRouteRouteChildren = {
  marketingIndexRoute: marketingIndexRoute,
}

const marketingRouteRouteWithChildren = marketingRouteRoute._addFileChildren(
  marketingRouteRouteChildren,
)

interface siteRouteRouteChildren {
  siteCoursesIndexRoute: typeof siteCoursesIndexRoute
  siteLeaderboardIndexRoute: typeof siteLeaderboardIndexRoute
  siteLearnIndexRoute: typeof siteLearnIndexRoute
  siteQuestsIndexRoute: typeof siteQuestsIndexRoute
  siteShopIndexRoute: typeof siteShopIndexRoute
}

const siteRouteRouteChildren: siteRouteRouteChildren = {
  siteCoursesIndexRoute: siteCoursesIndexRoute,
  siteLeaderboardIndexRoute: siteLeaderboardIndexRoute,
  siteLearnIndexRoute: siteLearnIndexRoute,
  siteQuestsIndexRoute: siteQuestsIndexRoute,
  siteShopIndexRoute: siteShopIndexRoute,
}

const siteRouteRouteWithChildren = siteRouteRoute._addFileChildren(
  siteRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  marketingRouteRoute: marketingRouteRouteWithChildren,
  siteRouteRoute: siteRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
